services:
  - type: web
    name: laravel-products
    env: php
    buildCommand: composer install --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error

